### ISSUE TITLE
Assignment Submission

### ISSUE THREAD

**Issue by KyLoc20** [ThaddeusJiang/react-assignment-hard#1]
Hi Jiang, I've seen your tweet about this assignment 2 months ago and set off building such a simple Twitter according to your requirements. Now I almost finished this job: [twitter-shadow](https://github.com/KyLoc20/twitter-shadow)🚩

Just to test my capability, it did take time and efforts to complete such an application from scratch (Even the UI lib 😛).

If you noticed this issue, I wish to talk with you more about this project and share some stuff with each other.

Thank you for providing such an object. I learned a lot from it! ⚔️

**Comment by KyLoc20** [comment]
> Hi Jiang, I've seen your tweet about this assignment 2 months ago and set off building such a simple Twitter according to your requirements. Now I almost finished this job: [twitter-shadow](https://github.com/KyLoc20/twitter-shadow)🚩
> 
> Just to test my capability, it did take time and efforts to complete such an application from scratch (Even the UI lib 😛).
> 
> If you noticed this issue, I wish to talk with you more about this project and share some stuff with each other.
> 
> Thank you for providing such an object. I learned a lot from it! ⚔️

**Comment by KyLoc20** [comment]
@ThaddeusJiang

**Comment by ThaddeusJiang** [comment]
Hi @KyLoc20  

I have reviewed your project, it is beautiful.
I am very glad to talk with you, let's talk in IM app, could you tell me your IM account? Twitter is ok.

**Comment by KyLoc20** [comment]
im (here)[https://twitter.com/CRa_SSus]
